apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: leoberto89/api-bootcamp-produto:v2
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        ports:
          - containerPort: 8080
        env:
          - name: MONGODB_URI
            value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin